# Generated by Django 5.0.6 on 2024-06-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="count_views",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество просмотров"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateField(
                auto_now_add=True,
                help_text="Введите дату создания",
                null=True,
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.CharField(
                blank=True,
                help_text="Человекопонятный URL",
                max_length=150,
                null=True,
                verbose_name="Человекопонятный URL",
            ),
        ),
    ]
