# Generated by Django 5.0.6 on 2024-05-20 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["id_category"],
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                help_text="Введите описание", verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_category",
            field=models.CharField(
                help_text="Введите категорию",
                max_length=150,
                verbose_name="Наименование",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateField(
                blank=True,
                help_text="Введите дату создания",
                null=True,
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                help_text="Введите описание", verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="id_category",
            field=models.ForeignKey(
                help_text="Введите категорию",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="catalog.category",
                verbose_name="ID категории",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_product",
            field=models.CharField(
                help_text="Введите продукт", max_length=150, verbose_name="Наименование"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Укажите изображение",
                null=True,
                upload_to="media/",
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(
                help_text="Введите цену за покупку", verbose_name="Цена за покупку"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateField(
                blank=True,
                help_text="Введите дату последнего изменения",
                null=True,
                verbose_name="Дата последнего изменения",
            ),
        ),
    ]
