# Generated by Django 5.0.6 on 2024-05-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_options_alter_category_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="manufactured_at",
            field=models.DateField(
                blank=True,
                help_text="Введите дату производства продукта",
                null=True,
                verbose_name="Дата производства продукта",
            ),
        ),
    ]
